version: '3.8'

services:
  yaraxserver:
    image: yaraxserver:latest
    network_mode: "host"
    command: ["./yaraxserver", "--host", "0.0.0.0", "--port", "7779"]
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/dbname"

