services:
  yaraxserver4:
    container_name: yaraxserver4
    image: yaraxserver:latest
    network_mode: "host"
    restart: "always"
    command: ["yaraxserver", "--host", "0.0.0.0","--port", "7779"]
    environment:
      DATABASE_URL: "postgres://postgres:Welcome1admin2024@localhost:5432/postgres"