version: '3.8'

services:
  yaraxserver:
    image: yaraxserver:latest
    network_mode: "host"
    command: ["./yaraxserver", "--host", "0.0.0.0", "--port", "7779"]
    environment:
      DATABASE_URL: "postgres://postgres:Welcome1admin2024@postgres:5432/postgres"
    volumes:
      - /lib64:/lib64
      - /lib:/lib