//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::yara_file::Entity as YaraFile;
pub use super::yara_rule_history::Entity as YaraRuleHistory;
pub use super::yara_rules::Entity as YaraRules;
